name: 🚀 Deploy to Cloud Run

on:
  push:
    branches:
      - produccion

env:
  PROJECT_ID: cloud-engineer-test-juanc
  REGION: us-central1
  SERVICE_NAME: prospect2-backend

jobs:
  deploy:

    name: 🔄 Build & Deploy to Cloud Run
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🔑 Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 🔧 Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'beta'

      - name: 🐳 Build & Push Docker Image
        run: |
          IMAGE="us-central1-docker.pkg.dev/$PROJECT_ID/backend-images/$SERVICE_NAME"
          gcloud builds submit --tag $IMAGE .

      - name: 🚀 Deploy to Cloud Run from Docker Image
        run: |
          IMAGE="us-central1-docker.pkg.dev/$PROJECT_ID/backend-images/$SERVICE_NAME"
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated